import * as React from "react";
import Head from "next/head";
import { Box } from "@mui/material";
import Popular from "../component/Page/Popular";
import styles from "../styles/Home.module.css";
import Footer from "../component/Page/Footer";
import HeroSection from "../component/Page/HeroSection";
import Header from "../component/Page/Header";
export default function Home() {
  return (
    <>
      <Head>
        <title>Netplox - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        
        <link rel="icon" href="/netplox.jpg" />
      </Head>
      <Box className={styles.container}>
        <Header />
        <HeroSection />
        <Popular />
        <Footer />
      </Box>
    </>
  );
}
